### ISSUE TITLE
Test orders aren't appearing for sellers under "Order History"

### ISSUE THREAD

**Issue by imkane** [webkul/multi-vendor-marketplace-lite-for-woocommerce#1]
I placed a test order, and I can only see it when logged in as my Seller as a "notification" (it doesn't appear under "Order History"), yet when I click the notification link for #22, it opens a page with an error.

Any ideas?

![selection-230](https://github.com/webkul/multi-vendor-marketplace-lite-for-woocommerce/assets/2041683/57c97643-25bc-456b-b872-432031fb3c3d)
![selection-228](https://github.com/webkul/multi-vendor-marketplace-lite-for-woocommerce/assets/2041683/d23ffccd-8288-476a-816a-bb3a4c6e7ee8)
![selection-229](https://github.com/webkul/multi-vendor-marketplace-lite-for-woocommerce/assets/2041683/6fae0b34-48ba-4bb3-93a9-98cee26f02fb)

**Comment by dineshyadav4wp** [comment]
@imkane Please check our reply to your support ticket https://webkul.uvdesk.com/en/member/ticket/view/509403

And share your stagging site details to debug it as it is working fine at our end and other clients' sites. No one has reported this before. 

We have checked it on our different servers. Please have a look at this screen recording. https://webkul.chatwhizz.com/share/view-recording/65dc31f4095e20057944d0fc

**Comment by imkane** [comment]
@dineshyadav4wp I replied to the support ticket :nerd_face:

**Comment by dineshyadav4wp** [comment]
@imkane We have added the compatibility with woocommerce cart and checkout blocks and also now supporting WooPayments. 

https://wordpress.org/plugins/multi-vendor-marketplace-lite-for-woocommerce/

Kindly update the plugin to the latest version and proceed. It will work now. 
thanks!

**Comment by dineshyadav4wp** [comment]
@imkane We have updated the plugin and We haven’t heard back from you in a while, so we are closing this issue.
